// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgYjrEsc3cRKpgqXBIefknNHsNZb-emyg',
    appId: '1:820348041446:web:bcc01e2a109d7b435be327',
    messagingSenderId: '820348041446',
    projectId: 'rimbarest-ad285',
    authDomain: 'rimbarest-ad285.firebaseapp.com',
    storageBucket: 'rimbarest-ad285.firebasestorage.app',
    measurementId: 'G-M1VQNV569E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6ozHYJf4U4fgrT8nlImqPUmmENrBJbAU',
    appId: '1:820348041446:android:369f58a87e1957a15be327',
    messagingSenderId: '820348041446',
    projectId: 'rimbarest-ad285',
    storageBucket: 'rimbarest-ad285.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5xUVXIH50cAbZHosrYrwM8u3f1Dx4HfU',
    appId: '1:820348041446:ios:bcae8f5bf02208475be327',
    messagingSenderId: '820348041446',
    projectId: 'rimbarest-ad285',
    storageBucket: 'rimbarest-ad285.firebasestorage.app',
    iosBundleId: 'com.example.rimbarest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5xUVXIH50cAbZHosrYrwM8u3f1Dx4HfU',
    appId: '1:820348041446:ios:bcae8f5bf02208475be327',
    messagingSenderId: '820348041446',
    projectId: 'rimbarest-ad285',
    storageBucket: 'rimbarest-ad285.firebasestorage.app',
    iosBundleId: 'com.example.rimbarest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgYjrEsc3cRKpgqXBIefknNHsNZb-emyg',
    appId: '1:820348041446:web:4dcc74b08162893f5be327',
    messagingSenderId: '820348041446',
    projectId: 'rimbarest-ad285',
    authDomain: 'rimbarest-ad285.firebaseapp.com',
    storageBucket: 'rimbarest-ad285.firebasestorage.app',
    measurementId: 'G-RCBSERYRLB',
  );
}
